In [22]:
# Example from Keras with some changes
# Binary classification

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout

# Generate dummy data
x_train = np.random.random((1000, 20))
y_train = np.random.randint(2, size=(1000, 1))
x_test = np.random.random((100, 20))
y_test = np.random.randint(2, size=(100, 1))

model = Sequential()
model.add(Dense(64, input_dim=20, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

model.fit(x_train, y_train,
          epochs=500,
          batch_size=128)
score = model.evaluate(x_test, y_test, batch_size=128)

Epoch 1/500
1000/1000 [==============================] - 3s 3ms/step - loss: 0.7088 - acc: 0.5210
Epoch 2/500
1000/1000 [==============================] - 0s 104us/step - loss: 0.6989 - acc: 0.5220
Epoch 3/500
1000/1000 [==============================] - 0s 94us/step - loss: 0.7108 - acc: 0.4900
Epoch 4/500
1000/1000 [==============================] - 0s 125us/step - loss: 0.7035 - acc: 0.4950
Epoch 5/500
1000/1000 [==============================] - 0s 81us/step - loss: 0.6952 - acc: 0.5370
Epoch 6/500
1000/1000 [==============================] - 0s 65us/step - loss: 0.6979 - acc: 0.4970
Epoch 7/500
1000/1000 [==============================] - 0s 51us/step - loss: 0.7044 - acc: 0.4840
Epoch 8/500
1000/1000 [==============================] - 0s 55us/step - loss: 0.6957 - acc: 0.5080
Epoch 9/500
1000/1000 [==============================] - 0s 60us/step - loss: 0.6943 - acc: 0.5300
Epoch 10/500
1000/1000 [==============================] - 0s 102us/step - loss: 0.6944 - acc: 0.5260
Epoch 1

Epoch 83/500
1000/1000 [==============================] - 0s 42us/step - loss: 0.6660 - acc: 0.5800
Epoch 84/500
1000/1000 [==============================] - 0s 39us/step - loss: 0.6644 - acc: 0.6010
Epoch 85/500
1000/1000 [==============================] - 0s 35us/step - loss: 0.6623 - acc: 0.6130
Epoch 86/500
1000/1000 [==============================] - 0s 35us/step - loss: 0.6579 - acc: 0.6100
Epoch 87/500
1000/1000 [==============================] - 0s 29us/step - loss: 0.6555 - acc: 0.5890
Epoch 88/500
1000/1000 [==============================] - 0s 35us/step - loss: 0.6624 - acc: 0.5950
Epoch 89/500
1000/1000 [==============================] - 0s 32us/step - loss: 0.6571 - acc: 0.6060
Epoch 90/500
1000/1000 [==============================] - 0s 38us/step - loss: 0.6585 - acc: 0.5920
Epoch 91/500
1000/1000 [==============================] - 0s 30us/step - loss: 0.6536 - acc: 0.6030
Epoch 92/500
1000/1000 [==============================] - 0s 40us/step - loss: 0.6491 - acc: 0.6210


1000/1000 [==============================] - 0s 29us/step - loss: 0.6177 - acc: 0.6630
Epoch 165/500
1000/1000 [==============================] - 0s 30us/step - loss: 0.6206 - acc: 0.6550
Epoch 166/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.6113 - acc: 0.6550
Epoch 167/500
1000/1000 [==============================] - 0s 32us/step - loss: 0.6073 - acc: 0.6660
Epoch 168/500
1000/1000 [==============================] - 0s 21us/step - loss: 0.6202 - acc: 0.6550
Epoch 169/500
1000/1000 [==============================] - 0s 26us/step - loss: 0.6087 - acc: 0.6620
Epoch 170/500
1000/1000 [==============================] - 0s 36us/step - loss: 0.6087 - acc: 0.6660
Epoch 171/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.6130 - acc: 0.6520
Epoch 172/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.6022 - acc: 0.6840
Epoch 173/500
1000/1000 [==============================] - 0s 32us/step - loss: 0.6313 - acc: 0.6490
Epoc

1000/1000 [==============================] - 0s 29us/step - loss: 0.5851 - acc: 0.6910
Epoch 246/500
1000/1000 [==============================] - 0s 26us/step - loss: 0.5673 - acc: 0.6900
Epoch 247/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.5795 - acc: 0.7000
Epoch 248/500
1000/1000 [==============================] - 0s 28us/step - loss: 0.5670 - acc: 0.7110
Epoch 249/500
1000/1000 [==============================] - 0s 33us/step - loss: 0.5754 - acc: 0.6930
Epoch 250/500
1000/1000 [==============================] - 0s 26us/step - loss: 0.5616 - acc: 0.7040
Epoch 251/500
1000/1000 [==============================] - 0s 32us/step - loss: 0.5865 - acc: 0.6880
Epoch 252/500
1000/1000 [==============================] - 0s 28us/step - loss: 0.5647 - acc: 0.6850
Epoch 253/500
1000/1000 [==============================] - 0s 26us/step - loss: 0.5607 - acc: 0.7200
Epoch 254/500
1000/1000 [==============================] - 0s 26us/step - loss: 0.5475 - acc: 0.7250
Epoc

1000/1000 [==============================] - 0s 42us/step - loss: 0.5350 - acc: 0.7230
Epoch 327/500
1000/1000 [==============================] - 0s 39us/step - loss: 0.5299 - acc: 0.7390
Epoch 328/500
1000/1000 [==============================] - 0s 40us/step - loss: 0.5240 - acc: 0.7480
Epoch 329/500
1000/1000 [==============================] - 0s 34us/step - loss: 0.5018 - acc: 0.7530
Epoch 330/500
1000/1000 [==============================] - 0s 30us/step - loss: 0.5369 - acc: 0.7260
Epoch 331/500
1000/1000 [==============================] - 0s 46us/step - loss: 0.5274 - acc: 0.7360
Epoch 332/500
1000/1000 [==============================] - 0s 32us/step - loss: 0.5268 - acc: 0.7460
Epoch 333/500
1000/1000 [==============================] - 0s 30us/step - loss: 0.5189 - acc: 0.7380
Epoch 334/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.5346 - acc: 0.7120
Epoch 335/500
1000/1000 [==============================] - 0s 40us/step - loss: 0.5209 - acc: 0.7400
Epoc

1000/1000 [==============================] - 0s 35us/step - loss: 0.4761 - acc: 0.7650
Epoch 407/500
1000/1000 [==============================] - 0s 30us/step - loss: 0.4936 - acc: 0.7470
Epoch 408/500
1000/1000 [==============================] - 0s 23us/step - loss: 0.4580 - acc: 0.7830
Epoch 409/500
1000/1000 [==============================] - 0s 28us/step - loss: 0.5010 - acc: 0.7530
Epoch 410/500
1000/1000 [==============================] - 0s 16us/step - loss: 0.4885 - acc: 0.7680
Epoch 411/500
1000/1000 [==============================] - ETA: 0s - loss: 0.5501 - acc: 0.695 - 0s 18us/step - loss: 0.5100 - acc: 0.7480
Epoch 412/500
1000/1000 [==============================] - 0s 24us/step - loss: 0.4839 - acc: 0.7590
Epoch 413/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.4951 - acc: 0.7390
Epoch 414/500
1000/1000 [==============================] - 0s 19us/step - loss: 0.4817 - acc: 0.7590
Epoch 415/500
1000/1000 [==============================] - 0s 27us/

1000/1000 [==============================] - 0s 21us/step - loss: 0.4818 - acc: 0.7510
Epoch 487/500
1000/1000 [==============================] - 0s 22us/step - loss: 0.4628 - acc: 0.7910
Epoch 488/500
1000/1000 [==============================] - 0s 18us/step - loss: 0.4701 - acc: 0.7670
Epoch 489/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.4731 - acc: 0.7680
Epoch 490/500
1000/1000 [==============================] - 0s 17us/step - loss: 0.4600 - acc: 0.7680
Epoch 491/500
1000/1000 [==============================] - 0s 16us/step - loss: 0.4752 - acc: 0.7680
Epoch 492/500
1000/1000 [==============================] - 0s 27us/step - loss: 0.4592 - acc: 0.7800
Epoch 493/500
1000/1000 [==============================] - 0s 14us/step - loss: 0.4525 - acc: 0.7870
Epoch 494/500
1000/1000 [==============================] - 0s 17us/step - loss: 0.4680 - acc: 0.7700
Epoch 495/500
1000/1000 [==============================] - 0s 20us/step - loss: 0.4843 - acc: 0.7590
Epoc

In [ ]:
score = model.evaluate(x_test, y_test, batch_size=128)

In [23]:
score

[0.9696159362792969, 0.6000000238418579]

In [26]:
model.predict(x_train[65:66], batch_size=None, verbose=0, steps=None)

array([[0.3007793]], dtype=float32)

In [20]:
x_train[0:1]

array([[0.3707813 , 0.36917273, 0.39499242, 0.8080693 , 0.87011206,
        0.18273051, 0.56256684, 0.3733149 , 0.19308319, 0.27128953,
        0.91808312, 0.22811958, 0.01034881, 0.93903448, 0.48915764,
        0.58804837, 0.76255463, 0.20342345, 0.09767187, 0.75315042]])

In [27]:
y_train[65:66]

array([[0]])