In [ ]:
# Creating Arrays

In [ ]:
# Import numpy library
import numpy as np

In [ ]:
# numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

np.array([1, 2, 3])

In [ ]:
np.array([[1, 2], [3, 4]])

In [ ]:
np.array([1, 2, 3], dtype=complex)

In [ ]:
# numpy.arange([start, ]stop, [step, ]dtype=None)

np.arange(3)


In [ ]:
np.arange(3.0)

In [ ]:
np.arange(3,7)

In [ ]:
np.arange(3,10,2)

In [ ]:
#1d 
np.random.rand(10)

In [ ]:
#2d 
np.random.rand(5,5)

#2d
np.random.rand(2,2)

In [ ]:
# 3d
np.random.rand(3,4,6)

In [ ]:
# numpy.empty(shape, dtype=float, order='C')

np.empty([4, 2])


In [ ]:
np.empty([2, 2], dtype=int)

In [ ]:
np.zeros((5,), dtype=int)

In [ ]:
np.zeros((5, 5, 7))

In [ ]:
np.ones((5,), dtype=int)

In [ ]:
np.ones((2, 1))

In [ ]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')[source]

np.eye(10,10, k=1)

In [ ]:
# numpy.random.random(size=None)

np.random.random_sample((5,))

In [ ]:
arr = np.arange(10)
arr

In [ ]:
# numpy.random.shuffle(x)

np.random.shuffle(arr)
arr

In [ ]:
# Inspecting Arrays

In [ ]:
a = np.random.rand(2,5)
a

In [ ]:
a.size

In [ ]:
a.shape

In [ ]:
a.ndim

In [ ]:
a.dtype

In [ ]:
# numpy.reshape(a, newshape, order='C')[source]

b = np.arange(6)
b

In [ ]:
b.ndim

In [ ]:
#1d -> 2 d

c = np.reshape(b,(2,3))
c

In [ ]:
c.ndim

In [ ]:
# 2d -> 3 d
d = np.reshape(c, c.shape + (1,))
d

In [ ]:
d.ndim

In [ ]:
# 3d -> 2d
e = np.reshape(d, (2, 3)) # C-like index ordering
e

In [ ]:
e.ndim

In [ ]:
# 2d -> 1d
f = np.reshape(e,(6))
f

In [ ]:
f.ndim

In [ ]:
a = np.array([[1,2], [3,4]])
a.flatten()



In [ ]:
a.flatten('F')

In [ ]:
x = np.arange(1, 7).reshape(2, 3)
x


In [ ]:
x.flat[1:]

In [ ]:
# Array Manipulation

x = np.arange(4).reshape((2,2))
x

In [ ]:
np.transpose(x)

In [64]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [71]:
a = np.array((1,2,3))
b = np.array((2,3,4))
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [72]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [73]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [74]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [75]:
np.vsplit(x, 2)


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [76]:
#The basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step (k\neq0). 
#This selects the m elements (in the corresponding dimension) with index values i, i + k, …, i + (m - 1) k where m = q + (r\neq0) and q and r are the quotient and remainder obtained by dividing j - i by k: j - i = q k + r, so that i + (m - 1) k < j.


x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]


array([1, 3, 5])

In [77]:
x[-2:10]

array([8, 9])

In [78]:
x[-3:3:-1]

array([7, 6, 5, 4])

In [79]:
#Assume n is the number of elements in the dimension being sliced. 
#Then, if i is not given it defaults to 0 for k > 0 and n - 1 for k < 0 . 
#If j is not given it defaults to n for k > 0 and -n-1 for k < 0 .
#If k is not given it defaults to 1. Note that :: is the same as : and means select all indices along this axis.

x[5:]

array([5, 6, 7, 8, 9])

In [85]:
x = np.array([[[1],[2],[3]], [[4],[5],[6]]])
x.shape

x[0:1]

array([[[1],
        [2],
        [3]]])

In [88]:

# x is your dataset
x = np.random.rand(10, 5)
#numpy.random.shuffle(x)
training, test = x[:8,:], x[8:,:]

In [89]:
training

array([[0.96600372, 0.65906476, 0.88649681, 0.08126485, 0.11693636],
       [0.82955136, 0.70182325, 0.17277297, 0.73926716, 0.37228217],
       [0.23154203, 0.25199448, 0.93050059, 0.83572575, 0.70136943],
       [0.65070691, 0.68810463, 0.80719497, 0.46474001, 0.24043614],
       [0.23196852, 0.01043216, 0.60220858, 0.63342098, 0.15427807],
       [0.64284865, 0.60476618, 0.91548865, 0.29823154, 0.68614135],
       [0.5540531 , 0.8147166 , 0.08716562, 0.53893829, 0.87906019],
       [0.93868007, 0.23927292, 0.28626717, 0.29433471, 0.13785526]])

In [90]:
test

array([[0.84278984, 0.92119618, 0.08891821, 0.05535071, 0.69673554],
       [0.58633979, 0.98329592, 0.64169076, 0.967271  , 0.85421108]])

In [91]:
x

array([[0.96600372, 0.65906476, 0.88649681, 0.08126485, 0.11693636],
       [0.82955136, 0.70182325, 0.17277297, 0.73926716, 0.37228217],
       [0.23154203, 0.25199448, 0.93050059, 0.83572575, 0.70136943],
       [0.65070691, 0.68810463, 0.80719497, 0.46474001, 0.24043614],
       [0.23196852, 0.01043216, 0.60220858, 0.63342098, 0.15427807],
       [0.64284865, 0.60476618, 0.91548865, 0.29823154, 0.68614135],
       [0.5540531 , 0.8147166 , 0.08716562, 0.53893829, 0.87906019],
       [0.93868007, 0.23927292, 0.28626717, 0.29433471, 0.13785526],
       [0.84278984, 0.92119618, 0.08891821, 0.05535071, 0.69673554],
       [0.58633979, 0.98329592, 0.64169076, 0.967271  , 0.85421108]])

In [92]:
x1 = np.arange(3)
x1

array([0, 1, 2])

In [93]:
x2 = np.arange(3)
x2

array([0, 1, 2])

In [94]:
x1 = np.arange(3)
x2 = np.arange(3)
np.add(x1, x2)

array([0, 2, 4])